siefkenj/pretext-book

- .gitignore
- package-lock.json
- package.json
- packages/fragment/README.md
- packages/fragment/build.js
- packages/fragment/package.json
- packages/fragment/src/cli/index.ts
- packages/fragment/src/index.ts
- packages/fragment/src/lib/extract-fragment-from-html.ts
- packages/fragment/src/lib/fragment-to-pretext.ts
- packages/fragment/src/lib/get-template-name.ts
- packages/fragment/src/lib/parse-fragment.ts
- packages/fragment/tests/extract.test.ts
- packages/fragment/tests/fragment.test.ts
- packages/fragment/tests/fragments/p1.xml
- packages/fragment/tests/rendered-fragments/p1.html
- packages/fragment/tests/templates/article.xml
- packages/fragment/tsconfig.json
- packages/pretext-playground/tsconfig.json
- tsconfig.build.json
Adds a CLI to allow expanding fragments on the command line as well as extracting the contents of a rendered fragment in the output HTML
> Fragment support with a CLI

- packages/fragment/basic-compile.sh
- packages/jsx/src/target/html/components/title.tsx
Also remove IDs from h1...h6 elements.
> Fix: Correct spaces in a classed-section.

- packages/fragment/basic-compile.sh
- packages/fragment/src/lib/fragment-to-pretext.ts
- packages/fragment/tests/templates/article.xml
- packages/fragment/tests/templates/book.xml
> Fix: Run validator on fragments

- packages/docs/pages/reference/elements/statement.mdx
This PR adds a description to the `<statement>` tag.
> The statement tag

- packages/docs/pages/reference/elements/c.mdx
> update c tag

- packages/docs/pages/reference/elements/c.mdx
- packages/docs/pages/reference/elements/ca.mdx
- packages/docs/pages/reference/elements/caption.mdx
> Add decription and example for caption tag

- packages/docs/compile-example.sh
- packages/fragment/basic-compile.sh
This PR changes the chunking level to 0 so that sections are not collapsed.
> Do not collapse sections

- packages/docs/pages/reference/elements/exercise.mdx
This PR adds the `<exercise>` tag.
> The exercise tag

- packages/docs/pages/reference/elements/doubleflat.mdx
- packages/docs/pages/reference/elements/doublesharp.mdx
- packages/docs/pages/reference/elements/flat.mdx
- packages/docs/pages/reference/elements/n.mdx
- packages/docs/pages/reference/elements/natural.mdx
- packages/docs/pages/reference/elements/sharp.mdx
First efforts.
Need to know about paragraphs within examples (separate email).
I have been feeding code into a pretext document to see that it compiles and how it looks.  Questions about rendering something like <n /> which PreTeXt does not like, requiring &lt; n /&gt; instead.  Will mdx handle it correctly?
Are these tags hyperlinked to each other?  For example if I refer to <flat/> inside the example for <sharp/> is there a link?
Having played with this only a bit, I am still fumbling with git.  For example, I would prefer to have pulled old commits and submitted a clean copy, but this seems not entirely straightforward.
> Music (flat, sharp, doubleflat, doublesharp, natural, n)

- packages/docs/pages/reference/elements/example.mdx
- packages/docs/pages/reference/elements/problem.mdx
- packages/docs/pages/reference/elements/question.mdx
For this collection of tags, I used the same tag description for each since they are very closely related and it might help a user to understand that which of question or problem to use is largely a personal choice (at least IMHO :) )
> Example like tags

- packages/docs/pages/reference/elements/algorithm.mdx
- packages/docs/pages/reference/elements/claim.mdx
- packages/docs/pages/reference/elements/corollary.mdx
- packages/docs/pages/reference/elements/fact.mdx
- packages/docs/pages/reference/elements/identity.mdx
- packages/docs/pages/reference/elements/lemma.mdx
- packages/docs/pages/reference/elements/proposition.mdx
- packages/docs/pages/reference/elements/theorem.mdx
> Theorem-like tags

- packages/docs/pages/reference/elements/sidebyside.mdx
I have provided a number of examples for this robust tag. I have tried to use your idea of a tabular to simulate images, but there is some visual information lost in that transition.
See what works for you and what you might like to see.
> First draft sidebyside

- README.md
Add the documentation website link to the readme.
> Update README.md to include documentation website

- packages/docs/pages/reference/elements/abbr.mdx
- packages/docs/pages/reference/elements/alert.mdx
- packages/docs/pages/reference/elements/angles.mdx
- packages/docs/pages/reference/elements/attr.mdx
- packages/docs/pages/reference/elements/dblbrackets.mdx
- packages/docs/pages/reference/elements/em.mdx
- packages/docs/pages/reference/elements/tag.mdx
- packages/docs/pages/reference/elements/tage.mdx
Before I get too carried away, how do these look?
> Some "inside paragraph" tags

- packages/docs/pages/reference/elements/convention.mdx
- packages/docs/pages/reference/elements/insight.mdx
- packages/docs/pages/reference/elements/note.mdx
- packages/docs/pages/reference/elements/observation.mdx
- packages/docs/pages/reference/elements/remark.mdx
Remark-like tags except for warning which had already been edited.
> Remark like

- packages/docs/scripts/auto-insert-attr-prop-descriptions.ts
- packages/docs/scripts/compute-optimized-schema.ts
- packages/docs/scripts/create-element-templates.ts
- packages/docs/scripts/dump-all-elements.ts
- packages/docs/tsconfig.json
- packages/pretext-playground/vite.config.ts
Add some `// @ts-ignore` commends to squash unneeded typescript warnings.
> Mute some warnings

- .github/workflows/build-test-and-deploy.yml
- .gitignore
- package-lock.json
- packages/jsx/package.json
- packages/jsx/update-schema-from-pretext-master.sh
Add script that will allow one to easily update the schema
> Rebuild schema

- packages/docs/pages/reference/elements/h.mdx
- packages/docs/pages/reference/elements/idx.mdx
- packages/docs/pages/reference/elements/see.mdx
- packages/docs/pages/reference/elements/seealso.mdx
Created with explanatory text since I presume the Index entries will not be rendered.
> Index-related entries

- packages/docs/pages/reference/elements/plaintitle.mdx
- packages/docs/pages/reference/elements/shorttitle.mdx
- packages/docs/pages/reference/elements/subtitle.mdx
- packages/docs/pages/reference/elements/title.mdx
We discussed issues in generating example of title-related tags in the absence of a title and TOC.  See what you think
> Title related

- .github/workflows/build-test-and-deploy.yml
The actions that this workflow uses were out of date.
> Update actions to most recent versions

- .github/workflows/update-schema.yml
This is the workflow to address #105.  
Note, that for this to work, settings for the repository need to enable GitHub Actions to create pull requests, and to have write access to the repository.
> Create update-schema workflow
